##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: solicitudes
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

# Configuración de PostgreSQL
adapters:
  r2dbc:
    host: localhost
    port: 5438
    database: dbCrediYa
    schema: public
    username: postgres
    password: root
